### ISSUE TITLE
Create an IntelliJ plug-in

### ISSUE THREAD

**Issue by helmbold** [kotlintest/kotlintest-intellij-plugin#2]
I think the single greatest step possible for KotlinTest would be adding a plug-in for IntelliJ. For example it is not possible to run a single test case from the open spec file. 

If we decide to develop it, the development should probably happen in another Git repo. This issue is here just as a starting point.

**Comment by yuan-raken** [comment]
@sksamuel I tested 3.3.0.1901-SNAPSHOT, 3.3.0.1735-SNAPSHOT, 3.3.0.1785-SNAPSHOT, with the latest plugin (3.3.0.7) and still doesn't work for me. 

```
    testCompile ('io.kotlintest:kotlintest-core:3.3.0.1901-SNAPSHOT')
    testCompile ('io.kotlintest:kotlintest-runner-junit5:3.3.0.1901-SNAPSHOT')
```

![image](https://user-images.githubusercontent.com/45988138/53280288-27390a00-377d-11e9-8105-87452128f8b2.png)

I can see the arrows but it doesn't matter which one I click, it runs all for me

**Comment by yuan-raken** [comment]
Another a problem is once I extend the FeatureSpec to another layer, the arrow won't be shown for me as well.

![image](https://user-images.githubusercontent.com/45988138/53280391-64ea6280-377e-11e9-939f-deef87d27ce7.png)

**Comment by sksamuel** [comment]
This should all be fixed in 3.3.0.8. It is for me anyway :)
You'll need to wait for Jetbrains to approve the update - takes 24-48hours
then it will appear as an update in Intellij automatically.

**Comment by atreyas** [comment]
I still cannot run single tests with 3.3.0.11. It seems to run all the tests on the IDE, although there are markers for each test.
